Weterynarz.Web/Areas/Admin/Controllers/MedicalExaminationTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;
using Weterynarz.Web.Models.NotifyMessage;
using Weterynarz.Domain.Repositories.Interfaces;
using Weterynarz.Domain.ViewModels.MedicalExaminationTypes;
using Microsoft.Extensions.Logging;
using Weterynarz.Basic.Const;
using Microsoft.AspNetCore.Authorization;

namespace Weterynarz.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Worker)]
    public class MedicalExaminationTypesController : AdminBaseController
    {
        private readonly IMedicalExaminationTypesRepository _medicalExaminationTypesRepository;
        private ILogger<MedicalExaminationTypesController> _logger;

        public MedicalExaminationTypesController(IMedicalExaminationTypesRepository medicalExaminationTypesRepository, ILogger<MedicalExaminationTypesController> logger)
        {
            _medicalExaminationTypesRepository = medicalExaminationTypesRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var listElements = _medicalExaminationTypesRepository.GetIndexViewModel().OrderBy(a => a.Name);
            var model = await PagingList.CreateAsync(listElements, 20, page);

            return View(model);
        }

        // GET: AnimalTypes/Create
        public IActionResult Create()
        {
            MedicalExaminationTypesManageViewModel model = new MedicalExaminationTypesManageViewModel();

            return View(model);
        }

        // POST: AnimalTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MedicalExaminationTypesManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _medicalExaminationTypesRepository.CreateNewType(model);

                Message message = new Message
                {
                    Text = "Jeeessttt",
                    OptionalText = "Badanie zostało dodane",
                    MessageStatus = Models.NotifyMessage.MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: AnimalTypes/Edit/5
        public IActionResult Edit(int id)
        {
            MedicalExaminationTypesManageViewModel model = _medicalExaminationTypesRepository.GetEditViewModel(id);
            if(model == null)
            {
                base.NotifyMessage("Nie znaleziono badania z takim identyfikatorem", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // POST: AnimalTypes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MedicalExaminationTypesManageViewModel model)
        {
            try
            {
                bool result = await _medicalExaminationTypesRepository.EditType(model);

                Message message = new Message
                {
                    Text = "Sukces !",
                    OptionalText = "Pomyślnie zapisano badanie",
                    MessageStatus = MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Wystąpił błąd podczas edycji");
                base.NotifyMessage("Wystąpił błąd podczas edycji", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }
        }

        // GET: AnimalTypes/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                bool result = await _medicalExaminationTypesRepository.DeleteType(id);

                Message message = new Message
                {
                    Text = "Sukces !",
                    OptionalText = "Pomyślnie usunięto badanie",
                    MessageStatus = MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Wystąpił błąd podczas usuwania");
                base.NotifyMessage("Wystąpił błąd podczas usuwania", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }
        }
    }
}

Weterynarz.Web/Areas/Admin/Views/MedicalExaminationTypes/Create.cshtml
@namespace Weterynarz.Domain.ViewModels.MedicalExaminationTypes
@model MedicalExaminationTypesManageViewModel
@{
    ViewData["Title"] = "Manage";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="MedicalExaminationTypes" asp-action="Index" asp-area="@AreaNames.Admin">Typy badań</a></li>
        <li class="breadcrumb-item active">Dodaj</li>
    </ol>
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form asp-controller="MedicalExaminationTypes" asp-action="Create" method="post">
                    <div class="card-header">
                        <strong>@ResAdmin.medicalExaminationTypesCreateView_headerForm</strong>
                    </div>
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="Name"></label>
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź nazwę">
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="Description"></label>
                                    <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input class="form-check-input" type="checkbox" asp-for="Active" checked="checked">
                                         Czy aktywny?
                                    </label>
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Dodaj</button>
                        <a asp-controller="MedicalExaminationTypes" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Weterynarz.Web/Areas/Admin/Views/MedicalExaminationTypes/Edit.cshtml
@namespace Weterynarz.Domain.ViewModels.MedicalExaminationTypes
@model MedicalExaminationTypesManageViewModel
@{
    ViewData["Title"] = "Manage";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="MedicalExaminationTypes" asp-action="Index" asp-area="@AreaNames.Admin">Typy badań</a></li>
        <li class="breadcrumb-item active">Dodaj</li>
    </ol>
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form asp-controller="MedicalExaminationTypes" asp-action="Edit" method="post">
                    <div class="card-header">
                        <strong>@ResAdmin.medicalExaminationTypesEditView_headerForm</strong>
                    </div>
                    <div class="card-body">

                        <div class="row">
                            <div class="col-sm-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            </div>
                        </div>

                        @Html.HiddenFor(m => m.Id)

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="Name"></label>
                                    <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź nazwę">
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label asp-for="Description"></label>
                                    <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-check">
                                    <label class="form-check-label">
                                        @Html.CheckBoxFor(m => m.Active, new { @class= "form-check-input" })
                                        Czy aktywny?
                                    </label>
                                </div>
                            </div>
                        </div>
                        <!--/.row-->

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Zapisz</button>
                        <a asp-controller="MedicalExaminationTypes" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Weterynarz.Web/Areas/Admin/Views/MedicalExaminationTypes/Index.cshtml
@namespace Weterynarz.Domain.ViewModels.MedicalExaminationTypes
@model PagingList<MedicalExaminationTypesIndexViewModel>
@{
    ViewData["Title"] = "Typy zwierząt";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item active" >Typy badań</li>
    </ol>
}

<div class="container">
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @ResAdmin.text_options
                </div>
                <div class="card-body">
                    <a class="btn btn-warning" asp-controller="MedicalExaminationTypes" asp-action="Create">@ResAdmin.button_add</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> @ResAdmin.medicalExaminationTypesIndex_listTypes
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nazwa</th>
                                <th>Opis</th>
                                <th>Data utworzenia</th>
                                <th>Aktywny</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td>@item.Description</td>
                                        <td>@item.CreationDate.ToString(FormatsDate.Date)</td>
                                        <td>@(item.Active ? Html.Raw("<span class='badge badge-success'>Aktywny</span>") : Html.Raw("<span class='badge badge-danger'>Nieaktywny</span>"))</td>
                                        <td class="text-right">
                                            <a href="@Url.Action("Edit", "MedicalExaminationTypes", new { area = AreaNames.Admin, id = item.Id})" class="btn btn-dark">Edytuj</a>
                                            <a href="@Url.Action("Delete", "MedicalExaminationTypes", new { area = AreaNames.Admin, id = item.Id })" id="btnDeleteType" class="btn btn-danger">Usuń</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr class="text-center">
                                    <td colspan="5">@ResAdmin.list_emptyRecords</td>
                                </tr>
                            }                            
                        </tbody>
                    </table>
                    <nav aria-label="Suppliers navigation example">
                        @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {

}