Weterynarz.Web/ViewComponents/TopNavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Weterynarz.Web.ViewComponents
{
    public class TopNavbarViewComponent : ViewComponent
    {
        public TopNavbarViewComponent()
        {

        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Weterynarz.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Weterynarz</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/components-font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/customAdmin.css" />
        <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.css">        
        <link rel="stylesheet" href="~/lib/bootstrap4-datetimepicker/css/bootstrap-datetimepicker.css" />
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.css">
        @* Template style *@
        <link rel="stylesheet" href="~/css/templateStyle/sb-admin.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/components-font-awesome/css/font-awesome.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/customAdmin.min.css" asp-append-version="true" />        
        <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/lib/bootstrap4-datetimepicker/css/bootstrap-datetimepicker.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" asp-append-version="true">
        @* Template style *@
        <link rel="stylesheet" href="~/css/templateStyle/sb-admin.min.css" asp-append-version="true" />        
    </environment>
</head>
<body class="fixed-nav bg-dark" id="page-top">

    @await Component.InvokeAsync("TopNavbar")

    <div class="content-wrapper">
        <div class="container-fluid mb-5">
            <!-- Breadcrumb -->
            @RenderSection("breadcrumb", false)

            @RenderBody()

            <!-- /.conainer-fluid -->
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/moment/moment.min.js"></script>
        <script src="~/lib/moment/moment-with-locales.min.js"></script>
        <script src="~/lib/Microsoft.jQuery.Unobtrusive.Ajax/jquery.unobtrusive-ajax.min.js"></script>
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery.easing/js/jquery.easing.js"></script>
        <script src="~/lib/bootstrap4-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/js/app/datetimepickerIconsFix.js"></script>
        <script src="~/lib/select2/dist/js/select2.js"></script>
        <script src="~/lib/sweetalert2/dist/sweetalert2.all.js"></script>
        <script src="~/js/app/appNotify.js"></script>
        @await Html.PartialAsync("_NotifyMessage")
        <script src="~/js/templateScripts/sb-admin.js"></script>        
        <script src="~/js/app/appFormats.js"></script>
        <script src="~/js/custom.js"></script>

    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/moment/moment.min.js" asp-append-version="true"></script>
        <script src="~/lib/moment/moment-with-locales.min.js" asp-append-version="true"></script>
        <script src="~/lib/Microsoft.jQuery.Unobtrusive.Ajax/jquery.unobtrusive-ajax.min.js" asp-append-version="true"></script>
        <script src="~/lib/popper.js/dist/umd/popper.min.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/app/datetimepickerIconsFix.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap4-datetimepicker/js/bootstrap-datetimepicker.min.js" asp-append-version="true"></script>
        <script src="~/lib/select2/dist/js/select2.min.js" asp-append-version="true"></script>
        <script src="~/lib/sweetalert2/dist/sweetalert2.all.js" asp-append-version="true"></script>
        <script src="~/js/app/appNotify.js" asp-append-version="true"></script>
        @await Html.PartialAsync("_NotifyMessage")
        <script src="~/js/templateScripts/app.js" asp-append-version="true"></script>
        <script src="~/js/app/appFormats.js" asp-append-version="true"></script>
        <script src="~/js/custom.min.js" asp-append-version="true"></script>

    </environment>

    @RenderSection("Scripts", required: false)
</body>



</html>

Weterynarz.Web/Areas/Admin/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Weterynarz | Logowanie</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/components-font-awesome/css/font-awesome.css" />

        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css">
        <link rel="stylesheet" href="~/css/loginPage.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/components-font-awesome/css/font-awesome.min.css" asp-append-version="true" />

        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="~/lib/sweetalert2/dist/sweetalert2.min.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/loginPage.min.css" asp-append-version="true" />
    </environment>

</head>
<body class="loginPage fullPage">
    <div class="container">        
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/sweetalert2/dist/sweetalert2.all.js"></script>
        <script src="~/js/app/appNotify.js"></script>
        @await Html.PartialAsync("_NotifyMessage")
        <script src="~/js/custom.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="~/lib/popper.js/dist/umd/popper.min.js" asp-append-version="true"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/sweetalert2/dist/sweetalert2.all.js" asp-append-version="true"></script>
        <script src="~/js/app/appNotify.js" asp-append-version="true"></script>
        @await Html.PartialAsync("_NotifyMessage")
        <script src="~/js/custom.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>

</html>