Weterynarz.Web/Areas/Admin/Controllers/DiseasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Weterynarz.Domain.Repositories.Interfaces;
using Weterynarz.Domain.ViewModels.Animal;
using ReflectionIT.Mvc.Paging;
using Weterynarz.Web.Models.NotifyMessage;
using Weterynarz.Domain.ViewModels.Disease;
using Microsoft.Extensions.Logging;
using Weterynarz.Basic.Const;
using Microsoft.AspNetCore.Authorization;

namespace Weterynarz.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Worker)]
    public class DiseasesController : AdminBaseController
    {
        private IDiseasesRepository _diseasesRepository;
        private ILogger<DiseasesController> _logger;

        public DiseasesController(IDiseasesRepository diseasesRepository, ILogger<DiseasesController> logger)
        {
            this._diseasesRepository = diseasesRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var listElements = _diseasesRepository.GetIndexViewModel().OrderBy(a => a.Name);
            var model = await PagingList.CreateAsync(listElements, 20, page);

            return View(model);
        }

        public IActionResult Create()
        {
            DiseaseManageViewModel model = new DiseaseManageViewModel();
            model.Active = true;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DiseaseManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _diseasesRepository.CreateNew(model);

                Message message = new Message
                {
                    Text = "Jeeessttt",
                    OptionalText = "Choroba została dodana",
                    MessageStatus = Models.NotifyMessage.MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            DiseaseManageViewModel model = _diseasesRepository.GetEditViewModel(id);
            if (model == null)
            {
                base.NotifyMessage("Nie znaleziono choroby", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DiseaseManageViewModel model)
        {
            try
            {
                await _diseasesRepository.Edit(model);

                Message message = new Message
                {
                    Text = "Sukces !",
                    OptionalText = "Pomyślnie zapisano",
                    MessageStatus = MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Wystąpił błąd podczas edycji");
                base.NotifyMessage("Wystąpił błąd podczas edycji", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }
        }
        
        //[HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _diseasesRepository.Delete(id);

                Message message = new Message
                {
                    Text = "Sukces !",
                    OptionalText = "Pomyślnie usunięto",
                    MessageStatus = MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Wystąpił błąd podczas usuwania");
                base.NotifyMessage("Wystąpił błąd podczas usuwania", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }
        }
    }
}

Weterynarz.Web/Areas/Admin/Views/Diseases/Create.cshtml
@namespace Weterynarz.Domain.ViewModels.Disease
@model DiseaseManageViewModel
@{
    ViewData["Title"] = "Dodaj chorobę";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="Diseases" asp-action="Index" asp-area="@AreaNames.Admin">Choroby</a></li>
        <li class="breadcrumb-item active">Dodaj</li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form asp-controller="Diseases" asp-action="Create" method="post">
                <div class="card-header">
                    <strong>@ResAdmin.diseasesCreateView_headerForm</strong>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-sm-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź nazwę">
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" asp-for="Active">
                                        Czy aktywna?
                                </label>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Dodaj</button>
                    <a asp-controller="Diseases" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                </div>
            </form>
        </div>
    </div>
</div>

Weterynarz.Web/Areas/Admin/Views/Diseases/Edit.cshtml
@namespace Weterynarz.Domain.ViewModels.Disease
@model DiseaseManageViewModel
@{
    ViewData["Title"] = "Edycja choroby";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="Diseases" asp-action="Index" asp-area="@AreaNames.Admin">Choroby</a></li>
        <li class="breadcrumb-item active">Edytuj</li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form asp-controller="Diseases" asp-action="Edit" method="post">
                <div class="card-header">
                    <strong>@ResAdmin.diseasesEditView_headerForm</strong>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-sm-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    </div>

                    @Html.HiddenFor(m => m.Id)

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź nazwę">
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" asp-for="Active">
                                    Czy aktywna?
                                </label>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Zapisz</button>
                    <a asp-controller="Diseases" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                </div>
            </form>
        </div>
    </div>
</div>

Weterynarz.Web/Areas/Admin/Views/Diseases/Index.cshtml
@namespace Weterynarz.Domain.ViewModels.Disease
@model PagingList<DiseaseIndexViewModel>
@{
    ViewData["Title"] = "Choroby";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item active" >Choroby</li>
    </ol>
}

<div class="row">
    <div class="col-md-12 mb-3">
        <div class="card">
            <div class="card-header">
                @ResAdmin.text_options
            </div>
            <div class="card-body">
                <a class="btn btn-warning" asp-controller="Diseases" asp-action="Create">@ResAdmin.button_add</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> @ResAdmin.diseasesIndex_list
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nazwa</th>
                            <th>Opis</th>
                            <th>Data utworzenia</th>
                            <th>Aktywny</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Any())
                        {
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Name</td>
                                    <td>@item.Description</td>
                                    <td>@item.CreationDate.ToString(FormatsDate.Date)</td>
                                    <td>@(item.Active ? Html.Raw("<span class='badge badge-success'>Aktywna</span>") : Html.Raw("<span class='badge badge-danger'>Nieaktywna</span>"))</td>
                                    <td class="text-right">
                                        <a href="@Url.Action("Edit", "Diseases", new { area = AreaNames.Admin, id = item.Id})" class="btn btn-dark">Edytuj</a>
                                        <a href="@Url.Action("Delete", "Diseases", new { area = AreaNames.Admin, id = item.Id })" id="btnDelete" class="btn btn-danger">Usuń</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr class="text-center">
                                <td colspan="5">@ResAdmin.list_emptyRecords</td>
                            </tr>
                        } 
                    </tbody>
                </table>
                <nav aria-label="Suppliers navigation example">
                    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
                </nav>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        //$(document).ready(function () {

        //    $('#btnDelete').on('click', function (e) {
        //        e.preventDefault();

        //        var $row = $(this).closest('tr');

        //    });

        //});
    </script>
}