Weterynarz.Web/Areas/Admin/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Weterynarz.Domain.Repositories.Interfaces;
using Weterynarz.Domain.ViewModels.Animal;
using ReflectionIT.Mvc.Paging;
using Weterynarz.Web.Models.NotifyMessage;
using Microsoft.Extensions.Logging;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Weterynarz.Basic.Const;

namespace Weterynarz.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = UserRoles.Admin + "," + UserRoles.Client + "," + UserRoles.Worker)]
    public class AnimalsController : AdminBaseController
    {
        private IAnimalRepository _animalsRepository;
        private ILogger<AnimalsController> _logger;

        public AnimalsController(IAnimalRepository animalsRepository, ILogger<AnimalsController> logger)
        {
            this._animalsRepository = animalsRepository;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var userId = User.Identity.GetUserId();
            var listElements = await _animalsRepository.GetIndexViewModel(userId);
            var listAnimals = listElements.OrderByDescending(a => a.CreationDate);
            var model = await PagingList.CreateAsync(listAnimals, 20, page);

            return View(model);
        }

        public IActionResult FillAnimalList(string userId)
        {
            var animalSelectList = _animalsRepository.GetUserAnimalsSelectList(userId);
            return Json(animalSelectList);
        }

        public IActionResult Create()
        {
            AnimalManageViewModel model = _animalsRepository.GetCreateNewViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AnimalManageViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _animalsRepository.CreateNew(model);

                Message message = new Message
                {
                    Text = "Jeeessttt",
                    OptionalText = "Zwierzak został dodany",
                    MessageStatus = Models.NotifyMessage.MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }

            model = _animalsRepository.GetAllSelectListProperties(model);
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            AnimalManageViewModel model = _animalsRepository.GetEditViewModel(id);
            if (model == null)
            {
                base.NotifyMessage("Nie znaleziono zwierzaka", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AnimalManageViewModel model)
        {
            if(ModelState.IsValid)
            { 
                try
                {
                    await _animalsRepository.Edit(model);

                    Message message = new Message
                    {
                        Text = "Sukces !",
                        OptionalText = "Pomyślnie zapisano",
                        MessageStatus = MessageStatus.success
                    };
                    base.NotifyMessage(message);

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "Wystąpił błąd podczas edycji", "Upppsss !");
                    base.NotifyMessage("Wystąpił błąd podczas edycji", "Upppsss !", MessageStatus.error);
                    return RedirectToAction("Index");
                }
            }

            model = _animalsRepository.GetAllSelectListProperties(model);
            return View(model);
        }
        
        //[HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _animalsRepository.Delete(id);

                Message message = new Message
                {
                    Text = "Sukces !",
                    OptionalText = "Pomyślnie usunięto",
                    MessageStatus = MessageStatus.success
                };
                base.NotifyMessage(message);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Wystąpił błąd podczas usuwania");
                base.NotifyMessage("Wystąpił błąd podczas usuwania", "Upppsss !", MessageStatus.error);
                return RedirectToAction("Index");
            }
        }
    }
}

Weterynarz.Web/Areas/Admin/Views/Animals/Create.cshtml
@namespace Weterynarz.Domain.ViewModels.Animal
@model AnimalManageViewModel
@{
    ViewData["Title"] = "Dodawanie zwierzęcia";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="Animals" asp-action="Index" asp-area="@AreaNames.Admin">Lista zwierząt</a></li>
        <li class="breadcrumb-item active">Dodaj</li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form asp-controller="Animals" asp-action="Create" method="post">
                <div class="card-header">
                    <strong>@ResAdmin.animalsCreateView_headerForm</strong>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-sm-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź imię">
                                <span asp-validation-for="Name" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="AnimalTypeId"></label>
                                <select asp-for="AnimalTypeId" class="form-control" asp-items="@Model.AnimalTypesSelectList" placeholder="Typ zwierzęcia"></select>
                                <span asp-validation-for="AnimalTypeId" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="BirthDay"></label>
                                <input type="text" class="form-control" id="BirthDay" name="BirthDay" value="@(Model.BirthDay == DateTime.MinValue ? "" : Model.BirthDay.ToString(FormatsDate.DateWithoutTime))" placeholder="Data urodzenia/przyjęcia" />
                                <span asp-validation-for="BirthDay" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>     
                        
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="OwnerId"></label>
                                <select asp-for="OwnerId" class="form-control" asp-items="@Model.OwnersSelectList" placeholder="Właściciel"></select>
                                <span asp-validation-for="OwnerId" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="DiseaseIds"></label>
                                <select asp-for="DiseaseIds" class="form-control" asp-items="@Model.DiseasesSelectList" placeholder="Przebyte choroby"></select>
                                <span asp-validation-for="DiseaseIds" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="MedicalExaminationIds"></label>
                                <select asp-for="MedicalExaminationIds" class="form-control" asp-items="@Model.MedicalExaminationSelectList" placeholder="Przebyte choroby"></select>
                                <span asp-validation-for="MedicalExaminationIds" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                                <span asp-validation-for="Description" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" asp-for="Active" checked="checked">
                                        Czy aktywny?
                                </label>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Dodaj</button>
                    <a asp-controller="Animals" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {            
            $('#BirthDay').datetimepicker({
                locale: 'pl',
                format: _formats_.dateFormatNoHours,
                useCurrent: false,
                keepOpen: false
            });

            $('#DiseaseIds').select2();

            $('#MedicalExaminationIds').select2();
        });
    </script>
}

Weterynarz.Web/Areas/Admin/Views/Animals/Edit.cshtml
@namespace Weterynarz.Domain.ViewModels.Animal
@model AnimalManageViewModel
@{
    ViewData["Title"] = "Edycja zwierzęcia";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item"><a asp-controller="Animals" asp-action="Index" asp-area="@AreaNames.Admin">Lista zwierząt</a></li>
        <li class="breadcrumb-item active">Edycja</li>
    </ol>
}

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <form asp-controller="Animals" asp-action="Edit" method="post">
                <div class="card-header">
                    <strong>@ResAdmin.animalsEditView_headerForm</strong>
                </div>
                <div class="card-body">

                    <div class="row">
                        <div class="col-sm-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input type="text" class="form-control" asp-for="Name" placeholder="Wprowadź imię">
                                <span asp-validation-for="Name" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="AnimalTypeId"></label>
                                <select asp-for="AnimalTypeId" class="form-control" asp-items="@Model.AnimalTypesSelectList" placeholder="Typ zwierzęcia"></select>
                                <span asp-validation-for="AnimalTypeId" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="BirthDay"></label>
                                <input type="text" class="form-control" id="BirthDay" name="BirthDay" value="@Model.BirthDay.ToString(FormatsDate.DateWithoutTime)" placeholder="Data urodzenia/przyjęcia" />
                                <span asp-validation-for="BirthDay" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="OwnerId"></label>
                                <select asp-for="OwnerId" class="form-control" asp-items="@Model.OwnersSelectList" placeholder="Właściciel"></select>
                                <span asp-validation-for="OwnerId" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="DiseaseIds"></label>
                                <select asp-for="DiseaseIds" class="form-control" asp-items="@Model.DiseasesSelectList" placeholder="Przebyte choroby"></select>
                                <span asp-validation-for="DiseaseIds" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="MedicalExaminationIds"></label>
                                <select asp-for="MedicalExaminationIds" class="form-control" asp-items="@Model.MedicalExaminationSelectList" placeholder="Przebyte choroby"></select>
                                <span asp-validation-for="MedicalExaminationIds" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <textarea rows="9" class="form-control" asp-for="Description" placeholder="Dodatkowy opis"></textarea>
                                <span asp-validation-for="Description" class="help-block text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" asp-for="Active">
                                    Czy aktywny?
                                </label>
                            </div>
                        </div>
                    </div>
                    <!--/.row-->

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> Zapisz</button>
                    <a asp-controller="Animals" asp-action="Index" asp-area="@AreaNames.Admin" class="btn btn-sm btn-danger pull-right"><i class="fa fa-ban"></i> Anuluj</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#BirthDay').datetimepicker({
                locale: 'pl',
                format: _formats_.dateFormatNoHours,
                useCurrent: false,
                keepOpen: false
            });

            $('#DiseaseIds').select2();

            $('#MedicalExaminationIds').select2();
        });
    </script>
}

Weterynarz.Web/Areas/Admin/Views/Animals/Index.cshtml
@namespace Weterynarz.Domain.ViewModels.Animal
@model PagingList<AnimalIndexViewModel>
@{
    ViewData["Title"] = "Zwierzęta";
}

@section breadcrumb {
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" asp-area="@AreaNames.Admin">Strona główna</a></li>
        <li class="breadcrumb-item active">Zwierzęta</li>
    </ol>
}

<div class="container">
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    @ResAdmin.text_options
                </div>
                <div class="card-body">
                    <a class="btn btn-warning" asp-controller="Animals" asp-action="Create">@ResAdmin.button_add</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-align-justify"></i> @ResAdmin.animalsIndex_listTypes
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nazwa</th>
                                <th>Typ</th>
                                <th>Data urodzenia</th>
                                <th>Właściciel</th>
                                <th>Aktywne</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Any())
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        <td>@item.Type</td>
                                        <td>@item.BirthDay.ToString(FormatsDate.DateWithoutTime)</td>
                                        <td>@item.Owner</td>
                                        <td>@(item.Active ? Html.Raw("<span class='badge badge-success'>Aktywny</span>") : Html.Raw("<span class='badge badge-danger'>Nieaktywny</span>"))</td>
                                        <td class="text-right">
                                            <a href="@Url.Action("Edit", "Animals", new { area = AreaNames.Admin, id = item.Id})" class="btn btn-dark">Edytuj</a>
                                            <a href="@Url.Action("Delete", "Animals", new { area = AreaNames.Admin, id = item.Id })" id="btnDeleteType" class="btn btn-danger">Usuń</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr class="text-center">
                                    <td colspan="6">@ResAdmin.list_emptyRecords</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <nav aria-label="Suppliers navigation example">
                        @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        //$(document).ready(function () {

        //    $('#btnDeleteType').on('click', function (e) {
        //        e.preventDefault();

        //        var $row = $(this).closest('tr');

        //    });

        //});
    </script>
}